services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: khalid
      POSTGRES_PASSWORD: 2527
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data